language: rust
cache: cargo
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
dist: xenial
